### ISSUE TITLE
XSS in room.dt

### ISSUE THREAD

**Issue by NVolcz** [rejectedsoftware/webchat-tutorial#2]
`http://127.0.0.1:8080/room?id=%3C/script%3E%3Cscript%3Ealert(1)%3b//&name=test`
Results in:
`<script src="scripts/chat.js"></script><script>connect("</script><script>alert(1);//", "test")</script>`

The current escaping is not considering the outer HTML context(room.dt)
`script connect(!{Json(id)}, !{Json(name)})`

**Comment by s-ludwig** [comment]
I wonder what the best way would be to make it less likely that this occurs in other applications. My approach to fix this would be to replace "/" with "\\/" in the generated JSON (anything I'm overlooking?). But it seems like there should be some kind of standard facility for inserting JSON into `<script>` nodes.

**Comment by s-ludwig** [comment]
Keeping in mind that the same pattern is probably already in use elsewhere, I've fixed this directly in the JSON generation code by always encoding "</" as "<\\/".

**Comment by adamdruppe** [comment]
> But it seems like there should be some kind of standard facility for inserting JSON into <script> nodes.

The / to \/ basically is the standard; it is what the html spec suggests and what most other libraries do. See: https://www.w3.org/TR/html4/appendix/notes.html#h-B.3.2
